url: https://deustodatacom.github.io
baseurl: /conferencia-datos/

# Site settings
title: Datos para la transformación social. Conferencia en Madrid, 12 de abril de 2018. 
email: m.gutierrez@deusto.es
description: "El 12 de abril nos veremos en una reunión inédita entre los diferentes agentes que trabajan con datos para debatir sobre el uso de los datos para la transformación social. ¡Te esperamos!"


# Team names, titles and social links
people:
- name: Miren Gutiérrez
  pic: miren-gutierrez
  position: Directora del <a href="https://www.deusto.es/cs/Satellite/deusto/es/masteres/estudios-masteres/experto-en-analisis-investigacion-y-comunicacion-de-datos/programa">Programa Experto en Análisis, Investigación y Comunicación de Datos</a>
  social:
    - title: twitter
      url: http://twitter.com/gutierrezmiren 

- name: Jorge Martín
  pic: jorge-martin
  position: <a href="http://www.jorgemartin.org/">Ilustrador</a> y facilitador gráfico
  social:
    - title: instagram
      url: https://www.instagram.com/yorsmartin/

- name: Miren Berasategi
  pic: miren-berasategi
  position: Investigadora del <a href="http://infocom.deusto.es">equipo de Comunicación</a> en la Universidad de Deusto
  social:
    - title: twitter
      url: http://twitter.com/mberasategi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/deustodata
  - title: linkedin
    url:
  - title: github
    url: http://github.com/deustodatacom/conferencia-datos

# Postal address (add as many lines as necessary)
address:
  - line: c/ Castelló 76
  - line: 28006 Madrid

# Build settings
markdown: kramdown
permalink: pretty