url: https://mberasategi.github.io
baseurl: /conferencia-datos/

# Site settings
title: Datos para la transformación social
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Miren Gutiérrez
  pic: miren-gutierrez
  position: Directora
  social:
    - title: twitter
      url: http://twitter.com/gutierrezmiren 

- name: Jorge Martín
  pic: jorge-martin
  position: Facilitador gráfico
  social:
    - title: instagram
      url: https://www.instagram.com/yorsmartin/

- name: Miren Berasategi
  pic: miren-berasategi
  position: Apoyo
  social:
    - title: twitter
      url: http://twitter.com/mberasategi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/deustodata
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: c/ Castelló 76
  - line: 28006 Madrid

# Build settings
markdown: kramdown
permalink: pretty