url: https://mberasategi.github.io
baseurl: /conferencia-datos/

# Site settings
title: Datos para la transformación social
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Miren Gutiérrez
  pic: 1
  position: Directora del <a href="https://www.deusto.es/cs/Satellite/deusto/es/masteres/estudios-masteres/experto-en-analisis-investigacion-y-comunicacion-de-datos/programa">Programa Experto en Análisis, Investigación y Comunicación de Datos</a>
  social:
    - title: twitter
      url: http://twitter.com/gutierrezmiren
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Jorge Martín
  pic: 2
  position: Facilitador gráfico
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/deustodata
  - title: linkedin
    url: http://stackoverflow.com/questions/tagged/jekyll


# Postal address (add as many lines as necessary)
address:
  - line: Castelló 76
  - line: 28006 Madrid

# Build settings
markdown: kramdown
permalink: pretty